version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build
          command: |
            chown -R $USER:$USER .
            docker-compose build
      - run:
          name: Lint with rubocop
          command: docker-compose run web bundle exec rubocop
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d
            sleep 20
            docker-compose exec web bin/rails db:setup
            docker-compose exec web yarn install
            docker-compose exec web bin/rails assets:precompile
            docker-compose exec web \
              curl --retry 20 --retry-delay 1 --retry-connrefused http://localhost:3000
            docker-compose exec web bin/rspec
            docker-compose logs web
