# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/clears', type: :request do
  # Clear. As you add validations to Clear, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  before(:each) do
    sign_in random_user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Clear.create! valid_attributes
      get clears_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      clear = Clear.create! valid_attributes
      get clear_url(clear)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_clear_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      clear = Clear.create! valid_attributes
      get edit_clear_url(clear)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Clear' do
        expect do
          post clears_url, params: { clear: valid_attributes }
        end.to change(Clear, :count).by(1)
      end

      it 'redirects to the created clear' do
        post clears_url, params: { clear: valid_attributes }
        expect(response).to redirect_to(clear_url(Clear.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Clear' do
        expect do
          post clears_url, params: { clear: invalid_attributes }
        end.to change(Clear, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post clears_url, params: { clear: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested clear' do
        clear = Clear.create! valid_attributes
        patch clear_url(clear), params: { clear: new_attributes }
        clear.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the clear' do
        clear = Clear.create! valid_attributes
        patch clear_url(clear), params: { clear: new_attributes }
        clear.reload
        expect(response).to redirect_to(clear_url(clear))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (to display the 'edit' template)" do
        clear = Clear.create! valid_attributes
        patch clear_url(clear), params: { clear: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested clear' do
      clear = Clear.create! valid_attributes
      expect do
        delete clear_url(clear)
      end.to change(Clear, :count).by(-1)
    end

    it 'redirects to the clears list' do
      clear = Clear.create! valid_attributes
      delete clear_url(clear)
      expect(response).to redirect_to(clears_url)
    end
  end
end
