import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAtom,
  faBurn,
  faCalendarDay,
  faChevronDown,
  faCogs,
  faDungeon,
  faFighterJet,
  faGhost,
  faHistory,
  faHourglassStart,
  faImage,
  faLaughWink,
  faLock,
  faLockOpen,
  faMapMarker,
  faMeteor,
  faMobile,
  faQuestionCircle,
  faShapes,
  faUserAstronaut
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAtom,
  faBurn,
  faCalendarDay,
  faChevronDown,
  faCogs,
  faDungeon,
  faFighterJet,
  faGhost,
  faHistory,
  faHourglassStart,
  faImage,
  faLaughWink,
  faLock,
  faLockOpen,
  faMapMarker,
  faMeteor,
  faMobile,
  faQuestionCircle,
  faShapes,
  faUserAstronaut
);
