# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe EscapeGamesController, type: :controller do
  before(:all) do
    @escape_game = create(:escape_game)
    @user = @escape_game.user
  end

  before(:each) do
    sign_in @user
  end

  describe 'GET #index' do
    it 'returns a success response' do
      get :index
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      get :show, params: { id: @escape_game.to_param }
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      get :edit, params: { id: @escape_game.to_param }
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      xit 'creates a new EscapeGame' do
        expect do
          post :create, params: { escape_game: @escape_game }
        end.to change(EscapeGame, :count).by(1)
      end

      xit 'redirects to the created escape_game' do
        post :create, params: { escape_game: @escape_game }
        expect(response).to redirect_to(EscapeGame.last)
      end
    end

    context 'with invalid params' do
      xit "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { escape_game: @escape_game }
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      xit 'updates the requested escape_game' do
        escape_game = @escape_game
        put :update, params: {
          id: escape_game.to_param,
          escape_game: new_attributes
        }
        escape_game.reload
        skip('Add assertions for updated state')
      end

      xit 'redirects to the escape_game' do
        escape_game = @escape_game
        put :update, params: {
          id: escape_game.to_param,
          escape_game: valid_attributes
        }
        expect(response).to redirect_to(escape_game)
      end
    end

    context 'with invalid params' do
      xit "returns a success response (i.e. to display the 'edit' template)" do
        escape_game = @escape_game
        put :update, params: {
          id: escape_game.to_param,
          escape_game: invalid_attributes
        }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested escape_game' do
      escape_game = @escape_game
      expect do
        delete :destroy, params: { id: escape_game.to_param }
      end.to change(EscapeGame, :count).by(-1)
    end

    it 'redirects to the escape_games list' do
      escape_game = @escape_game
      delete :destroy, params: { id: escape_game.to_param }
      expect(response).to redirect_to(escape_games_url)
    end
  end
end
